/**A program that allows users to submit values. User can enter values (l ,L,h,H )means L =1,2,3 H=4,5,6 and compare
 * with computer simulation values from 1-6 whether the guesser is correct or not.
 * if user input q exit program and display the number of time that you win.
 * @Author Patharanan Papakang
 * @vesion 1.0,14/01/2022
 * ID: 643040207-4
 * Sec: 2
 */
package papakang.patharanan.lab4;

import java.util.Scanner;

public class diceGame {

  static int win = 0; // round the user wins.
  static int round = 0; // round the user input correct.

  /**
   * This methods is get input and computer random
   */
  public static void playGame() {
    Scanner input = new Scanner(System.in);

    while (true) {
      System.out.print("Enter your guess (l,L,h,H): ");
      String guess_by_user = input.nextLine(); //user input l,L,h,or H
      int max = 6;
      int min = 1;
      int rand = min + (int) (Math.random() * ((max - min) + 1)); // random computer choice from 1 up to 6.
      int answer_by_computer = rand;
      // If input q or Q exit program.
      if (guess_by_user.equalsIgnoreCase("q")) {
        break;
      }
      // If don't input a value l,L,h or H display Please enter only l,L,h, or H
      //When input only l,L,h, or H call method determineResult
      else if (
        !guess_by_user.equalsIgnoreCase("l") &&
        !guess_by_user.equalsIgnoreCase("h")
      ) {
        System.out.println("Please enter only l,L,h, or H");
        continue;
      } else {
        determineResult(answer_by_computer, guess_by_user);
        round++;
      }
    }
    input.close();
  }

  /**
   *The methods is compare the values generated by the computer to l and h
   *and compare the user input values with the computer.
   * @param answer_by_computer is value generated by the computer
   * @param guess_by_user  is  value entered by the user
   * @return  answer by computer
   */
  static String determineResult(int answer_by_computer, String guess_by_user) {
    String answerCom = "";

    // If the computer random 1,2, or 3 then it is the value l and random 4,5, or 6 then it is the value h.
    if (
      answer_by_computer == 1 ||
      answer_by_computer == 2 ||
      answer_by_computer == 3
    ) {
      answerCom = "l";
    } else {
      answerCom = "h";
    }
    System.out.println("Computer rolls the number " + answer_by_computer);
    System.out.println("You guess " + guess_by_user);

    // If user input is equal to the generated value, user wins and if user input does not match,computer win.
    if (guess_by_user.equalsIgnoreCase(answerCom)) {
      System.out.println("You wins!");
      win++;
    } else {
      System.out.println("Computer wins!");
    }

    return answerCom;
  }

  /**
   * This method calculates the value the user wins from all plays.
   */
  public static void displayStats() {
    Double result = (double) win / round * 100;
    System.out.println(
      "The number of time that you win is " +
      win +
      " and it is about " +
      String.format("%.2f", result) +
      "%" +
      " out of all number of wins"
    );
  }

  /**
   *
   * use method playGame
   * use method displayStats
   */
  public static void main(String[] args) {
    playGame();
    displayStats();
  }
}
